### ISSUE TITLE
crashes with some MSIL executables

### ISSUE THREAD

**Issue by MerX1030** [brad-sp/cuckoomon-modified#23]
I don't know if this a known/old issue but do you know the cause on why cuckoomon crashes MSIL executables?
Some hashes I was testing:
MD5 f0a6f59ca338067d7489b01d05179fdc
SHA1    00f33c199b77c4e2e458d7e7204ec1a45b78c557

MD5 ed1746e8320ffa5d0ad1cb269bc8dfc2
SHA1    308acbe16bfae0504d2b9979ce73981376159917

MD5 a8a9469e5211caa023054e7641313500
SHA1    7425afefd8132c4010a0313ffcbe762ad7d9611b

**Comment by brad-sp** [comment]
Thanks, looking into this.

**Comment by brad-sp** [comment]
Should be fixed with the latest version, can you confirm?

**Comment by MerX1030** [comment]
Sorry for late response. I was away for a while. It seems the samples still crashes in my case triggering the Windows Error Reporting tool.

**Comment by brad-sp** [comment]
Is it reproducible each time?  Which process crashes?  I just ran all three again with no issues, but I did previously observe problems with vbc.exe crashing sporadically.  That should be unrelated to the initial issue though.

**Comment by MerX1030** [comment]
It's different each time. Sometimes the main executable crashes. Sometimes its RegAsm.exe. Sometimes its vbc.exe.
Will try some tests again.

**Comment by brad-sp** [comment]
If you could compile a debug version, and give me the reported exceptions, that would be helpful.
